### ISSUE TITLE
Please clarify the difference with the existing tool

### ISSUE THREAD

**Issue by pcav** [zsiki/AttributeSplit#1]
An apparently identical function exists under Vector menu.

**Comment by zsiki** [comment]
yeh, I missed that :(
I've revoked my plugin, only slight differences are.
Sorry for the noise.

**Comment by pcav** [comment]
Thanks Siki for understanding. It would be great if you could join forces and help us improving the existing tools, who suffer from various major flaws.

**Comment by zsiki** [comment]
I can join to help.
Can you shed light on where to start?

**Comment by pcav** [comment]
I believe this thread is a good starting point: https://lists.osgeo.org/pipermail/qgis-psc/2015-November/003579.html
In short, we detected serious errors in current fTools and Processing, and we are looking for a fix.
Thanks!
